parameters:
    pim_volume_monitoring.persistence.query.average_max_attributes_per_family.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\AverageMaxAttributesPerFamily
    pim_volume_monitoring.persistence.query.average_max_options_per_attribute.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\AverageMaxOptionsPerAttribute
    pim_volume_monitoring.persistence.query.average_max_product_values.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\AverageMaxProductValues
    pim_volume_monitoring.persistence.query.count_attributes.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountAttributes
    pim_volume_monitoring.persistence.query.count_categories.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountCategories
    pim_volume_monitoring.persistence.query.count_category_trees.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountCategoryTrees
    pim_volume_monitoring.persistence.query.count_channels.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountChannels
    pim_volume_monitoring.persistence.query.count_families.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountFamilies
    pim_volume_monitoring.persistence.query.count_locales.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountLocales
    pim_volume_monitoring.persistence.query.count_localizable_and_scopable_attributes.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountLocalizableAndScopableAttributes
    pim_volume_monitoring.persistence.query.count_localizable_attributes.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountLocalizableAttributes
    pim_volume_monitoring.persistence.query.count_scopable_attributes.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountScopableAttributes
    pim_volume_monitoring.persistence.query.count_products.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountProducts
    pim_volume_monitoring.persistence.query.count_product_models.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountProductModels
    pim_volume_monitoring.persistence.query.count_variant_products.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountVariantProducts
    pim_volume_monitoring.persistence.query.count_product_values.class: Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Query\Sql\CountProductValues

services:
    pim_volume_monitoring.persistence.query.average_max_attributes_per_family:
        class: '%pim_volume_monitoring.persistence.query.average_max_attributes_per_family.class%'
        arguments:
            - '@database_connection'
            - '%attributes_per_family_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.average_max_query }

    pim_volume_monitoring.persistence.query.average_max_options_per_attribute:
        class: '%pim_volume_monitoring.persistence.query.average_max_options_per_attribute.class%'
        arguments:
            - '@database_connection'
            - '%options_per_attribute_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.average_max_query }

    pim_volume_monitoring.persistence.query.average_max_product_values:
        class: '%pim_volume_monitoring.persistence.query.average_max_product_values.class%'
        arguments:
            - '@database_connection'
            - '%options_per_attribute_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.average_max_query }

    pim_volume_monitoring.persistence.query.count_attributes:
        class: '%pim_volume_monitoring.persistence.query.count_attributes.class%'
        arguments:
            - '@database_connection'
            - '%attributes_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_categories:
        class: '%pim_volume_monitoring.persistence.query.count_categories.class%'
        arguments:
            - '@database_connection'
            - '%categories_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_category_trees:
        class: '%pim_volume_monitoring.persistence.query.count_category_trees.class%'
        arguments:
            - '@database_connection'
            - '%category_trees_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_channels:
        class: '%pim_volume_monitoring.persistence.query.count_channels.class%'
        arguments:
            - '@database_connection'
            - '%channels_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_families:
        class: '%pim_volume_monitoring.persistence.query.count_families.class%'
        arguments:
            - '@database_connection'
            - '%families_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_locales:
        class: '%pim_volume_monitoring.persistence.query.count_locales.class%'
        arguments:
            - '@database_connection'
            - '%locales_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_localizable_and_scopable_attributes:
        class: '%pim_volume_monitoring.persistence.query.count_localizable_and_scopable_attributes.class%'
        arguments:
            - '@database_connection'
            - '%localizable_and_scopable_attributes_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_localizable_attributes:
        class: '%pim_volume_monitoring.persistence.query.count_localizable_attributes.class%'
        arguments:
            - '@database_connection'
            - '%localizable_attributes_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_scopable_attributes:
        class: '%pim_volume_monitoring.persistence.query.count_scopable_attributes.class%'
        arguments:
            - '@database_connection'
            - '%scopable_attributes_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_products:
        class: '%pim_volume_monitoring.persistence.query.count_products.class%'
        arguments:
            - '@database_connection'
            - '%products_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_product_models:
        class: '%pim_volume_monitoring.persistence.query.count_product_models.class%'
        arguments:
            - '@database_connection'
            - '%product_models_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_variant_products:
        class: '%pim_volume_monitoring.persistence.query.count_variant_products.class%'
        arguments:
            - '@database_connection'
            - '%variant_products_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }

    pim_volume_monitoring.persistence.query.count_product_values:
        class: '%pim_volume_monitoring.persistence.query.count_product_values.class%'
        arguments:
            - '@database_connection'
            - '%product_models_limit%'
        tags:
            - { name: pim_volume_monitoring.persistence.count_query }


