config:
    config:
        pimfront/product-grid/application/configuration/filter-model:
            property:
                enabled:
                    model: pimfront/product-grid/domain/model/filter/property/boolean
                    label: Status
            attribute:
                pim_catalog_boolean:
                    model: pimfront/product-grid/domain/model/filter/attribute/boolean
            operator:
                ALL: pimfront/product-grid/domain/model/filter/operator/all
                '=': pimfront/product-grid/domain/model/filter/operator/equal
            value:
                - pimfront/product-grid/application/configuration/value

        pimfront/product-grid/application/configuration/filter-view:
            property:
                enabled:
                    view: pimfront/product-grid/application/component/filter/boolean
            attribute:
                pim_catalog_boolean:
                    view: pimfront/product-grid/application/component/filter/boolean
