config:
    config:
        pimfront/product-grid/application/configuration/filter-model:
            property:
                enabled:
                    model: pimfront/product-grid/domain/model/filter/property/boolean
                    label: Status
            attribute:
                pim_catalog_boolean:
                    model: pimfront/product-grid/domain/model/filter/attribute/boolean
                pim_catalog_identifier:
                    model: pimfront/product-grid/domain/model/filter/attribute/text
            operator:
                ALL: pimfront/product-grid/domain/model/filter/operator/all
                'CONTAINS': pimfront/product-grid/domain/model/filter/operator/contains
                'DOES NOT CONTAIN': pimfront/product-grid/domain/model/filter/operator/does-not-contain
                '=': pimfront/product-grid/domain/model/filter/operator/equal
                'IN LIST': pimfront/product-grid/domain/model/filter/operator/in-list
                'EMPTY': pimfront/product-grid/domain/model/filter/operator/is-empty
                'STARTS WITH': pimfront/product-grid/domain/model/filter/operator/starts-with
            value:
                - pimfront/product-grid/application/configuration/value

        pimfront/product-grid/application/configuration/filter-view:
            property:
                enabled:
                    view: pimfront/product-grid/application/component/filter/boolean
            attribute:
                pim_catalog_boolean:
                    view: pimfront/product-grid/application/component/filter/boolean
                pim_catalog_identifier:
                    view: pimfront/product-grid/application/component/filter/text
